exports.menu = [
  {
    id: 1,
    name: "Пицца Маргарита",
    description: "Классическая пицца с помидорами, моцареллой и базиликом.",
    price: 10.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 2,
    name: "Пепперони Пицца",
    description: "Пицца с острыми колбасками пепперони и сыром.",
    price: 11.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 3,
    name: "Пицца Гавайская",
    description: "Пицца с ветчиной и ананасами.",
    price: 12.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 4,
    name: "Пицца BBQ Цыпленок",
    description: "Пицца с барбекю-цыпленком, красным луком и соусом барбекю.",
    price: 13.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 5,
    name: "Пицца Вегетарианская",
    description: "Пицца с грибами, сладким перцем, оливками и томатным соусом.",
    price: 11.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 6,
    name: "Пицца Мексиканская",
    description: "Пицца с молотым мясом, горячими перцами, фасолью и сыром.",
    price: 12.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 7,
    name: "Пицца Карбонара",
    description: "Пицца с беконом, яйцом и пармезаном.",
    price: 13.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 8,
    name: "Пицца Морепродукты",
    description: "Пицца с морскими гребешками, креветками и кальмарами.",
    price: 14.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 9,
    name: "Пицца С артишоками и шпинатом",
    description: "Пицца с артишоками, шпинатом, моцареллой и оливковым маслом.",
    price: 12.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 10,
    name: "Пицца Супер Мясная",
    description: "Пицца с ветчиной, беконом, пепперони и мясным фаршем.",
    price: 14.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 11,
    name: "Пицца С грибами и трагуффелями",
    description: "Пицца с шампиньонами, трагуффельным маслом и пармезаном.",
    price: 15.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 12,
    name: "Пицца Барбекю Гриль",
    description: "Пицца с говядиной, курицей, луком и соусом барбекю.",
    price: 13.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 13,
    name: "Пицца Фруктовая",
    description: "Пицца с яблоками, грушами и карамельным соусом.",
    price: 12.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 14,
    name: "Пицца Четыре Сыра",
    description: "Пицца с горгонзолой, пармезаном, моцареллой и рикоттой.",
    price: 13.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 15,
    name: "Пицца Тунец и Лосось",
    description: "Пицца с тунцом, лососем, красным луком и соусом терияки.",
    price: 16.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 16,
    name: "Пицца Овощная",
    description: "Пицца с томатами, баклажанами, цуккини и болгарским перцем.",
    price: 11.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 17,
    name: "Пицца Романа",
    description: "Пицца с рукколой, пармезаном и бальзамическим уксусом.",
    price: 12.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 18,
    name: "Пицца С Креветками и Лососем",
    description: "Пицца с креветками, лососем и крем-фрешем.",
    price: 15.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 19,
    name: "Пицца Тайская",
    description: "Пицца с курицей, ананасами и соусом чили.",
    price: 13.49,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },
  {
    id: 20,
    name: "Пицца Специальная",
    description: "Пицца с артишоками, ветчиной, грибами и оливками.",
    price: 14.99,
    thumbnail: "pizza.jpg",
    type: "pizza",
  },

  {
    id: 21,
    name: "Сет №1",
    description: "Сет суши и роллов",
    items: [
      { id: 1, name: "Пицца Маргарита", quantity: 2 },
      { id: 20, name: "Пицца Специальная", quantity: 2 },
    ],
    price: 25.99,
    type: "set",
  },
  {
    id: 22,
    name: "Сет №2",
    description: "Сет суши и сашими",
    items: [
      { id: 19, name: "Пицца Тайская", quantity: 1 },
      { id: 1, name: "Пицца Маргарита", quantity: 2 },
      { id: 20, name: "Пицца Специальная", quantity: 2 },
    ],
    price: 28.99,
    type: "set",
  },
  {
    id: 23,
    name: "Сет №3",
    description: "Сет суши и роллов",
    items: [
      { id: 1, name: "Пицца Маргарита", quantity: 1 },
      { id: 20, name: "Пицца Специальная", quantity: 1 },
    ],
    price: 25.99,
    type: "set",
  },
  {
    id: 24,
    name: "Сет №4",
    description: "Сет суши и сашими",
    items: [
      { id: 19, name: "Пицца Тайская", quantity: 2 },
      { id: 1, name: "Пицца Маргарита", quantity: 2 },
    ],
    price: 28.99,
    type: "set",
  },
  {
    id: 25,
    name: "Сет №5",
    description: "Сет суши и роллов",
    items: [
      { id: 1, name: "Пицца Маргарита", quantity: 4 },
      { id: 20, name: "Пицца Специальная", quantity: 4 },
    ],
    price: 25.99,
    type: "set",
  },
  {
    id: 26,
    name: "Сет №6",
    description: "Сет суши и сашими",
    items: [
      { id: 19, name: "Пицца Тайская", quantity: 1 },
      { id: 20, name: "Пицца Специальная", quantity: 2 },
    ],
    price: 28.99,
    type: "set",
  },
];
